name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.AffixPlugin
author: LazyGon
api-version: '1.16'
depend: ["LuckPerms", "Vault"]
commands:
  affix:
    description: "Manipulate this plugin."
    permission: "affix.command.affix"
  prefix:
    description: "Manipulate prefix."
    permission: "affix.command.prefix"
  suffix:
    description: "Manipulate suffix."
    permission: "affix.command.suffix"

permissions:
  affix.*:
    description: Includes all permission.
    default: op
    children:
      affix.command.*: true
      affix.prefix.*: true
      affix.suffix.*: true

  # Command permissions.
  affix.command.*:
    description: "Permission for all commands for this plugin."
    default: op
    children:
      affix.command.affix: true
      affix.command.prefix: true
      affix.command.suffix: true
  affix.command.affix.*:
    description: "Permission for /affix <args...>"
    default: op
    children:
      affix.command.affix: true
      affix.command.affix.reload: true
      affix.command.affix.setprice: true

  affix.command.affix:
    description: "Permission for /affix <args>"
    default: op
  affix.command.affix.reload:
    description: "Permission for /affix reload"
    default: op
  affix.command.affix.setprice:
    description: "Permission for /prefix setprice <prefix|suffix>"
    default: op
  affix.command.prefix:
    description: "Permission for /prefix <args...>"
    default: op
  affix.command.suffix:
    description: "Permission for /suffix <args...>"
    default: op

  # Prefix related parent permissions.
  affix.prefix.*:
    description: All permissions for manipulating prefix.
    default: op
    children:
      affix.command.prefix: true
      affix.prefix.add.*: true
      affix.prefix.set.*: true
      affix.prefix.unset.*: true
      affix.prefix.remove.*: true
      affix.prefix.list.*: true
  affix.prefix.add.*:
    description: Parent permission for adding prefix.
    default: op
    children:
      affix.prefix.add: true
      affix.prefix.add.other: true
      affix.prefix.add.expire: true
      affix.prefix.add.unique: true
      affix.prefix.add.bypassprice: true
  affix.prefix.set.*:
    description: Parent permission for setting prefix.
    default: op
    children:
      affix.prefix.set: true
      affix.prefix.set.other: true
  affix.prefix.unset.*:
    description: Parent permission for unsetting prefix.
    default: op
    children:
      affix.prefix.unset: true
      affix.prefix.unset.other: true
  affix.prefix.remove.*:
    description: Parent permission for removing owned prefix.
    default: op
    children:
      affix.prefix.remove: true
      affix.prefix.remove.other: true
  affix.prefix.list.*:
    description: Parent permission for listing prefix.
    default: op
    children:
      affix.prefix.list: true
      affix.prefix.list.other: true

  # Prefix related child permissions. 
  affix.prefix.add:
    description: Permission for adding no expire and no unique prefix for yourself.
    default: op
  affix.prefix.add.other:
    description: Permission for adding prefix to other.
    default: op
  affix.prefix.add.expire:
    description: Permission for adding expired prefix.
    default: op
  affix.prefix.add.unique:
    description: Permission for adding unique prefix.
    default: op
  affix.prefix.add.bypassprice:
    description: Permission for adding prefix for free.
    default: op

  affix.prefix.set:
    description: Permission for setting no expire prefix for yourself.
    default: op
  affix.prefix.set.other:
    description: Permission for setting prefix to other.
    default: op

  affix.prefix.unset:
    description: Permission for unsetting your prefix.
    default: op
  affix.prefix.unset.other:
    description: Permission for unsetting others' prefix.
    default: op

  affix.prefix.remove:
    description: Permission for removeing your prefix.
    default: op
  affix.prefix.remove.other:
    description: Permission for removeing others' prefix.
    default: op

  affix.prefix.list:
    description: Permission for listing your prefix.
    default: op
  affix.prefix.list.other:
    description: Permission for listing others' prefix.
    default: op

  # Suffix related parent permissions.
  affix.suffix.*:
    description: All permissions for manipulating suffix.
    default: op
    children:
      affix.command.suffix: true
      affix.suffix.add.*: true
      affix.suffix.set.*: true
      affix.suffix.unset.*: true
      affix.suffix.remove.*: true
      affix.suffix.list.*: true
  affix.suffix.add.*:
    description: Parent permission for adding suffix.
    default: op
    children:
      affix.suffix.add: true
      affix.suffix.add.other: true
      affix.suffix.add.expire: true
      affix.suffix.add.unique: true
      affix.suffix.add.bypassprice: true
  affix.suffix.set.*:
    description: Parent permission for setting suffix.
    default: op
    children:
      affix.suffix.set: true
      affix.suffix.set.other: true
  affix.suffix.unset.*:
    description: Parent permission for unsetting suffix.
    default: op
    children:
      affix.suffix.unset: true
      affix.suffix.unset.other: true
  affix.suffix.remove.*:
    description: Parent permission for removing owned suffix.
    default: op
    children:
      affix.suffix.remove: true
      affix.suffix.remove.other: true
  affix.suffix.list.*:
    description: Parent permission for listing suffix.
    default: op
    children:
      affix.suffix.list: true
      affix.suffix.list.other: true

  # Suffix related child permissions. 
  affix.suffix.add:
    description: Permission for adding no expire and no unique suffix for yourself.
    default: op
  affix.suffix.add.other:
    description: Permission for adding suffix to other.
    default: op
  affix.suffix.add.expire:
    description: Permission for adding expired suffix.
    default: op
  affix.suffix.add.unique:
    description: Permission for adding unique suffix.
    default: op
  affix.suffix.add.bypassprice:
    description: Permission for adding suffix for free.
    default: op

  affix.suffix.set:
    description: Permission for setting no expire suffix for yourself.
    default: op
  affix.suffix.set.other:
    description: Permission for setting suffix to other.
    default: op

  affix.suffix.unset:
    description: Permission for unsetting your suffix.
    default: op
  affix.suffix.unset.other:
    description: Permission for unsetting others' suffix.
    default: op

  affix.suffix.remove:
    description: Permission for removeing your suffix.
    default: op
  affix.suffix.remove.other:
    description: Permission for removeing others' suffix.
    default: op

  affix.suffix.list:
    description: Permission for listing your suffix.
    default: op
  affix.suffix.list.other:
    description: Permission for listing others' suffix.
    default: op